### ISSUE TITLE
Lowest Common Ancestor of a binary tree

### ISSUE THREAD

**Issue by hijajoo** [ProAlgos/ProAlgos-Cpp#154]
I would like to do an implementation of Lowest Common Ancestor of a binary tree in C++.
Problem statement:
Given the root of a Binary tree, and two nodes, find the lowest common ancestor of both nodes and return it.

**Comment by harsha-vardhan-2** [comment]
Is this issue still open? I'd like to work on this.

**Comment by alxmjo** [comment]
Thanks for your interest! Please refer to our notes in #169, and note that that PR was implemented with the previous organization scheme, rather than the current scheme of code in header file and unit tests in `.cpp` file.  So yes, please feel free to start working on this, just keep that stuff in mind and make sure your commits are against and consistent with the `reorganise` branch. 

Also, if you're new to the repo and want to get your feet wet, a great way to do that is to migrate an algorithm to the new organization scheme, à la #201 and #202.

**Comment by ankur54** [comment]
Hi!! I would like to contribute to this issue if it is still open
