### ISSUE TITLE
How about some graph algorithms?

### ISSUE THREAD

**Issue by khannagautam** [ProAlgos/ProAlgos-Cpp#170]
Algorithms like BFS , DFS , Dijkstra, Bellman Ford and Floyd Warshall could be added.

**Comment by khannagautam** [comment]
I would like to add my implementations of these algortihms. 

Let me know if I can work on this.

**Comment by faheel** [comment]
Graph algorithms are really important. It's just that as I mentioned in #70, it's first necessary to implement the graph data structure (both directed and undirected) so that all graph algorithms use the same interface for graphs. As you can see already, I didn't get the time to implement it yet, but now since you've brought up the issue I'll get working on it ASAP because I too want to have as many graph algorithms in this repo as possible.

**Comment by faheel** [comment]
Also, note that the issue for graph algorithms is #70, so please continue any future discussion there. Though, I'll still keep this issue open until the graph data structure is implemented.

**Comment by ankur54** [comment]
I can implement Bellman Ford and Floyd Warshall algorithm. May I?
