### ISSUE TITLE
Still in active development?

### ISSUE THREAD

**Issue by alxmjo** [ProAlgos/ProAlgos-Cpp#175]
The most recent commit on this repo is from February. Is it still being maintained?

**Comment by faheel** [comment]
I was working on reorganising the project and on improving the documentation (in both the code and Markdown) on the [`reorganise`](https://github.com/faheel/Algos/tree/reorganise) branch, but that was a while ago and since then I got into other projects and wasn't able to spend time on maintaining Algos.

I intend to get back at it as soon as I can, but that would be in about a month from now. So if anyone would like to help in maintaining the repo as a collaborator, that would be a huge help and I would really appreciate that.

**Comment by alxmjo** [comment]
I'd love to help. I'm in the middle of a software/firmware internship and am realizing that working through this repo was one of the best things I did to prepare. There's a lot of teaching and learning potential here so I'd really like to help keep it up.

Do you have a to-do list of changes that you'd like to make? Or are you just working through issues? How can I help?

**Comment by faheel** [comment]
@alxmjo That's great! I'll create a project board with the tasks that need to be done first. Having a clear road-map and organizing / cleaning up open issues and PRs would make it easier for everyone to contribute. Give me a day or two to set up the project board and then we can start collaborating on the tasks.

**Comment by alxmjo** [comment]
@faheel Awesome! Looking forward to helping out.

**Comment by faheel** [comment]
@alxmjo Sorry for the late response. I have created a few projects for now. So we can start cleaning up the issues and reviewing pending PRs now. I've sent you an invite to become a collaborator.
