### ISSUE TITLE
Contributing new languages

### ISSUE THREAD

**Issue by furahadamien** [ProAlgos/ProAlgos-Cpp#254]
I want to contribute to this repository but my C++ knowledge is not solid. Can I make contributions in java? The repository description says that the algorithms are mostly in C++ but I don't see any that is not in C++.

**Comment by alxmjo** [comment]
Thanks for your interest, Furaha. As you point out, the repo is solely C++ at this point, but adding other languages is something we'd like to do in the future. Faheel mentioned Go the other day, and I have a few other languages I'd love to see included.

All of that said, we want to be thoughtful about how we add languages, since one of the strengths of this project is that each algorithm is verified via unit tests, and we employ Travis for continuous integration. Different languages have different requirements in these regards, hence being thoughtful about how they're added.

I'll leave it to @Faheel to comment further. For now, it might be worthwhile to imagine (and share here) what you think the addition of Java to the repo might look like. You can assume that the general organization (directories, READMEs, etc.) would be the same as for the C++ repos. What about unit tests? How would you separate implementation (as we've done with C++ header files)? What about continuous integration?

**Comment by furahadamien** [comment]
Ooh yeah. Thanks for the response. I get what you mean. So basically if you were to allow contributing in another language I would have to build a similar set-up that you have in C++, but in the specific language that I want(java in my case). I will try to see if I can contribute in C++ because I feel like if I were to go ahead with my proposal, I would still need someone else to help with stuff like writing unit tests.

**Comment by alxmjo** [comment]
Sounds good. I think this is worth keeping open as the point of contact for discussions related to new languages.

**Comment by faheel** [comment]
I too would like to have implementations in more languages (such as Go, Kotlin, Rust, Elixir and maybe even Python, Ruby and JavaScript/TypeScript), but I still haven't been able to figure out which approach would be the best to proceed with:

1. ### Mono-repo approach

   Create a sub-directory for each language, like it is for C++.

   #### Pros

    1. All of the code lives in one repo, which means the repo will have more activity and exposure.

   #### Cons

   1. Whenever files are committed, the code for only those languages whose files have been modified will need to be built and tested. For this, a custom shell script needs to be written that identifies the language directories that have been modified in the last commit, and run the build/test scripts for each of those languages.

   1. Managing issues, PRs and project boards will be more challenging as each of them will need to be individually tagged with the language they relate to. This would require extra effort from the collaborators, and also from those looking to find whether an issue/PR exists for _**X**_ algorithm or data structure in _**Y**_ language.

1. ### Multi-repo approach

   Rename this repo to `Algos-Cpp`, create a different repo for each language, and add links to all of them in a new repo that will be named `Algos`.

   #### Pros

   1. Separation of concerns, i.e., the code, CI builds, issues, PRs, projects and even collaborators for different languages will be separate, and thus easier to manage.

   #### Cons

   (Can't think of any at the moment, except that the activity will be fragmented across multiple repos, which would mean that each repo gets different amounts of exposure. But that's only fair I guess.)

**Comment by faheel** [comment]
Now that I've tried to list out the pros and cons, I think that the multi-repo approach will be better.

**Comment by alxmjo** [comment]
Closing based on conversation above. Thanks for bringing it up, @furahadamien.
