### ISSUE TITLE
Add Heap's algorithm for string permutations

### ISSUE THREAD

**Issue by a-moreira** [ProAlgos/ProAlgos-Cpp#336]
I'd like to add the Heap's Algorithm to generate all permutations of a string. I've already implemented it according to the guidelines. Just need to polish some things up.

**Comment by alxmjo** [comment]
Great! Let us know if you have any questions.

**Comment by a-moreira** [comment]
@alxmjo Actually I have one. The Heap's Algorithm trusts the input has no duplicate elements since it does not distinguish between repeated permutations. I could deal with this by making it return a `std::set` with the permutations, but that would add an additional `log n` complexity. How should I proceed?

**Comment by alxmjo** [comment]
I think that since the algorithm is predicated on the understanding that each element is unique it's okay to assume that and forgo the set implementation. This brings up a whole other conversation about verifying algorithm input, but as I said, I think that's a separate conversation.

Go ahead and implement it the way you had planned and then we can address issues as they come up.

**Comment by a-moreira** [comment]
@alxmjo All right. I just added the pull request.
