### ISSUE TITLE
Adding a Tower of Hanoi problem

### ISSUE THREAD

**Issue by Satyamjay** [ProAlgos/ProAlgos-Cpp#49]
Tower of hanoi is a classic example of recursion.I think it should be added in the list.

**Comment by faheel** [comment]
To contribute code for this issue, create a folder named `Recursion`, which would have a file named `TowerOfHanoi.cpp`.

**Comment by Korel** [comment]
Hello, i was looking for some basic ideas to start coding and found this issue. I wrote some code from a basic algorithm from Wikipedia and it might not be ideal but it would be great if you could give some feedback. It says "We don't support that file type" for .cpp, i don't know why. So i am sending the .cpp file in a zip. Thanks in advance and have a nice day.
[TowerOfHanoi.cpp.zip](https://github.com/faheel/Algos/files/1023695/TowerOfHanoi.cpp.zip)

**Comment by faheel** [comment]
Hi @Korel!
Since you are new to programming, I suggest that you first take a look at the repository, clone it, try compiling existing code, run it, mess around with it, tweak it, add something new etc., while learning about **Git** - the version control system, and also about **GitHub** - this website that uses Git at the back-end (behind the scenes) while also providing many useful features for managing open-source projects (such as discussing issues, reviewing code etc.).
Once you're done with that you'll have a better understanding of how to use GitHub and how to contribute code to a project. Here are some links that you'll find helpful:
- [Git Tutorial](https://try.github.io/levels/1/challenges/1) (**recommended**)
- [GitHub Help](https://help.github.com/categories/bootcamp/)

I'll be looking forward to reviewing your [pull request](https://help.github.com/articles/about-pull-requests/)!

**Comment by ShumWengSang** [comment]
I'm not exactly new to programming, but am looking to start helping out in open source projects so as to increase my breadth. If no one is working on this, I would like to dip my hands into it.

**Comment by faheel** [comment]
@ShumWengSang Thank you for your interest in taking this up! However, there already are 2 pull requests (#50 and #53) regarding the Tower of Hanoi problem, one of which is under review and the other is awaiting changes.
If you wish, you can contribute some other algorithm's implementation to the project.
